PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX mu:<http://mu.semte.ch/vocabularies/core/>
PREFIX ext:<http://mu.semte.ch/vocabularies/ext/>
PREFIX bestuurseenheidscode: <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/sessions> {
    <http://data.lblod.info/id/gebruiker/b902a388-4cb8-41d6-bc4d-0cd8382fc55d> a foaf:Person;
            mu:uuid "b902a388-4cb8-41d6-bc4d-0cd8382fc55d";
            foaf:firstName "Example";
            foaf:familyName "Organisation";
            foaf:member <http://data.lblod.info/id/bestuurseenheid/10b49274-d46b-4308-88b1-3bdf7e996985>;
            foaf:account <http://data.lblod.info/id/account/8fe61b88-1cca-47be-a75a-448183b8f666>.
    <http://data.lblod.info/id/account/8fe61b88-1cca-47be-a75a-448183b8f666> a foaf:OnlineAccount;
            mu:uuid "8fe61b88-1cca-47be-a75a-448183b8f666";
            foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
            ext:sessionRole "LBHackathon-FakeRole".

    <http://data.lblod.info/id/bestuurseenheid/10b49274-d46b-4308-88b1-3bdf7e996985> a besluit:Bestuurseenheid;
      mu:uuid "10b49274-d46b-4308-88b1-3bdf7e996985" .

  }
};
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/gebruiker/b902a388-4cb8-41d6-bc4d-0cd8382fc55d> a foaf:Person;
            mu:uuid "b902a388-4cb8-41d6-bc4d-0cd8382fc55d";
            foaf:firstName "Example";
            foaf:familyName "Organisation";
            foaf:member <http://data.lblod.info/id/bestuurseenheid/10b49274-d46b-4308-88b1-3bdf7e996985>;
            foaf:account <http://data.lblod.info/id/account/8fe61b88-1cca-47be-a75a-448183b8f666>.
    <http://data.lblod.info/id/account/8fe61b88-1cca-47be-a75a-448183b8f666> a foaf:OnlineAccount;
            mu:uuid "8fe61b88-1cca-47be-a75a-448183b8f666";
            foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
            ext:sessionRole "LBHackathon-FakeRole".

    <http://data.lblod.info/id/bestuurseenheid/10b49274-d46b-4308-88b1-3bdf7e996985> a besluit:Bestuurseenheid;
      mu:uuid "10b49274-d46b-4308-88b1-3bdf7e996985" .

  }
};
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/sessions> {
    <http://data.lblod.info/id/gebruiker/554d0b0f-2218-4ecf-9031-26a87697a92d> a foaf:Person;
            mu:uuid "554d0b0f-2218-4ecf-9031-26a87697a92d";
            foaf:firstName "Example";
            foaf:familyName "Municipality";
            foaf:member <http://data.lblod.info/id/bestuurseenheid/7f116c5f-dcfa-4747-9077-a941645dcb5c>;
            foaf:account <http://data.lblod.info/id/account/a2b2cd8b-1a77-41a3-8140-2d77457d4f95>.
    <http://data.lblod.info/id/account/a2b2cd8b-1a77-41a3-8140-2d77457d4f95> a foaf:OnlineAccount;
            mu:uuid "a2b2cd8b-1a77-41a3-8140-2d77457d4f95";
            foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
            ext:sessionRole "LBHackathon-FakeRole".

    <http://data.lblod.info/id/bestuurseenheid/7f116c5f-dcfa-4747-9077-a941645dcb5c> a besluit:Bestuurseenheid;
      mu:uuid "7f116c5f-dcfa-4747-9077-a941645dcb5c" .
  }
};
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/gebruiker/554d0b0f-2218-4ecf-9031-26a87697a92d> a foaf:Person;
            mu:uuid "554d0b0f-2218-4ecf-9031-26a87697a92d";
            foaf:firstName "Example";
            foaf:familyName "Municipality";
            foaf:member <http://data.lblod.info/id/bestuurseenheid/7f116c5f-dcfa-4747-9077-a941645dcb5c>;
            foaf:account <http://data.lblod.info/id/account/a2b2cd8b-1a77-41a3-8140-2d77457d4f95>.
    <http://data.lblod.info/id/account/a2b2cd8b-1a77-41a3-8140-2d77457d4f95> a foaf:OnlineAccount;
            mu:uuid "a2b2cd8b-1a77-41a3-8140-2d77457d4f95";
            foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
            ext:sessionRole "LBHackathon-FakeRole".

    <http://data.lblod.info/id/bestuurseenheid/7f116c5f-dcfa-4747-9077-a941645dcb5c> a besluit:Bestuurseenheid;
      mu:uuid "7f116c5f-dcfa-4747-9077-a941645dcb5c" .
  }
};

